@baseUrl = http://localhost:8080
@orderId = {{createOrder.response.body.id}}

### Healthcheck
GET {{baseUrl}}/health
Content-Type: application/json
###

### Criar pedido
# @name createOrder
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "customer_id": "customer-42",
  "items": [
    {
      "product_id": "prod-01",
      "product_name": "Tênis Runner X",
      "quantity": 2,
      "unit_price": 199.90
    },
    {
      "product_id": "prod-02",
      "product_name": "Camiseta Runner X",
      "quantity": 1,
      "unit_price": 59.90
    },
    {
      "product_id": "prod-03",
      "product_name": "Bola de futebol",
      "quantity": 1,
      "unit_price": 100.00
    },
    {
      "product_id": "prod-04",
      "product_name": "Carrinho de bebê",
      "quantity": 1,
      "unit_price": 200.00
    },
    {
      "product_id": "prod-05",
      "product_name": "Cadeira de bebê",
      "quantity": 1,
      "unit_price": 300.00
    }
  ]
}
###

### Buscar pedido por ID
# Crie o pedido previamente para buscar pelo ID
GET {{baseUrl}}/orders/{{orderId}}
Accept: application/json

###

### Atualizar status do pedido para criado
PATCH {{baseUrl}}/orders/{{orderId}}/status
Content-Type: application/json

{
  "status": "criado"
}

### Atualizar status do pedido para em_processamento
PATCH {{baseUrl}}/orders/{{orderId}}/status
Content-Type: application/json

{
  "status": "em_processamento"
}

###

### Atualizar status do pedido para enviado
PATCH {{baseUrl}}/orders/{{orderId}}/status
Content-Type: application/json

{
  "status": "enviado"
}

###

### Atualizar status do pedido para entregue
PATCH {{baseUrl}}/orders/{{orderId}}/status
Content-Type: application/json

{
  "status": "entregue"
}
